# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_home_conta.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Page_home_conta(object):
    """
    Essa é uma classe para a pagina de Home da conta
    """
    def setupUi(self, MainWindow):
        # Configurar a janela principal
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(701, 393)
        MainWindow.setMinimumSize(QtCore.QSize(701, 393))
        MainWindow.setMaximumSize(QtCore.QSize(701, 393))
        MainWindow.setStyleSheet("background-color: rgb(221, 221, 221);")
        # Criar um widget central para a janela
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")

        # Criar botão para depósito
        self.btn_depositar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_depositar.setGeometry(QtCore.QRect(20, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_depositar.setFont(font)
        self.btn_depositar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_depositar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_depositar.setObjectName("btn_depositar")

        # Criar botão para saque
        self.btn_sacar = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sacar.setGeometry(QtCore.QRect(160, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_sacar.setFont(font)
        self.btn_sacar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sacar.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_sacar.setObjectName("btn_sacar")

        # Criar botão para transferencia
        self.btn_transferencia = QtWidgets.QPushButton(self.centralwidget)
        self.btn_transferencia.setGeometry(QtCore.QRect(300, 230, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_transferencia.setFont(font)
        self.btn_transferencia.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_transferencia.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_transferencia.setObjectName("btn_transferencia")

        # Criar botão para historico
        self.btn_historico = QtWidgets.QPushButton(self.centralwidget)
        self.btn_historico.setGeometry(QtCore.QRect(450, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_historico.setFont(font)
        self.btn_historico.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_historico.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_historico.setObjectName("btn_historico")

        # Criar botão para excluir conta
        self.btn_excluir = QtWidgets.QPushButton(self.centralwidget)
        self.btn_excluir.setGeometry(QtCore.QRect(590, 230, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.btn_excluir.setFont(font)
        self.btn_excluir.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_excluir.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_excluir.setObjectName("btn_excluir")

        # Criar botão para sair
        self.btn_sair = QtWidgets.QPushButton(self.centralwidget)
        self.btn_sair.setGeometry(QtCore.QRect(310, 330, 81, 23))
        self.btn_sair.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_sair.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(202, 202, 202);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(122, 122, 122);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btn_sair.setObjectName("btn_sair")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(10, 300, 681, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 180, 701, 20))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lb_op = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.lb_op.setFont(font)
        self.lb_op.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_op.setObjectName("lb_op")
        self.horizontalLayout.addWidget(self.lb_op)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(400, 80, 135, 51))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lb_limite = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.lb_limite.setFont(font)
        self.lb_limite.setObjectName("lb_limite")
        self.verticalLayout.addWidget(self.lb_limite)
        self.txt_limite = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_limite.setFont(font)
        self.txt_limite.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_limite.setObjectName("txt_limite")
        self.verticalLayout.addWidget(self.txt_limite)
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(0, 10, 701, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName("label_4")
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(550, 80, 135, 51))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget2)
        self.label.setObjectName("label")
        self.verticalLayout_2.addWidget(self.label)
        self.txt_numero = QtWidgets.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_numero.setFont(font)
        self.txt_numero.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_numero.setObjectName("txt_numero")
        self.verticalLayout_2.addWidget(self.txt_numero)
        self.txt_ola_nome = QtWidgets.QLabel(self.centralwidget)
        self.txt_ola_nome.setGeometry(QtCore.QRect(40, 80, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_ola_nome.setFont(font)
        self.txt_ola_nome.setObjectName("txt_ola_nome")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(40, 110, 131, 41))
        self.widget.setObjectName("widget")
        self.btn_verSaldo = QtWidgets.QPushButton(self.widget)
        self.btn_verSaldo.setGeometry(QtCore.QRect(90, 10, 31, 21))
        self.btn_verSaldo.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.url_verSaldo = ("\n"
"\n"
"QPushButton{\n"
"image: url(banco_interface/imgs/svgviewer-output.svg);\n"
"border-radius: 5px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_verSaldo.setStyleSheet(self.url_verSaldo)
        self.btn_verSaldo.setText("")
        self.btn_verSaldo.setObjectName("btn_verSaldo")
        self.txt_saldo = QtWidgets.QLabel(self.widget)
        self.txt_saldo.setGeometry(QtCore.QRect(0, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.txt_saldo.setFont(font)
        self.txt_saldo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_saldo.setObjectName("txt_saldo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 701, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_depositar.setText(_translate("MainWindow", "Depositar"))
        self.btn_sacar.setText(_translate("MainWindow", "Sacar"))
        self.btn_transferencia.setText(_translate("MainWindow", "Transferência"))
        self.btn_historico.setText(_translate("MainWindow", "Histórico"))
        self.btn_excluir.setText(_translate("MainWindow", "Excluir conta"))
        self.btn_sair.setText(_translate("MainWindow", "Sair"))
        self.lb_op.setText(_translate("MainWindow", "OPERAÇÕES"))
        self.lb_limite.setText(_translate("MainWindow", "Limite da conta: "))
        self.txt_limite.setText(_translate("MainWindow", ""))
        self.label_4.setText(_translate("MainWindow", "BANCO DE RESERVAS"))
        self.label.setText(_translate("MainWindow", "Número da conta: "))
        self.txt_numero.setText(_translate("MainWindow", ""))
        self.txt_ola_nome.setText(_translate("MainWindow", ""))
        self.btn_verSaldo.setToolTip(_translate("MainWindow", "<html><head/><body><p>Ver saldo</p></body></html>"))
        self.btn_verSaldo.setWhatsThis(_translate("MainWindow", "<html><head/><body><p>Ver saldo</p></body></html>"))
        self.txt_saldo.setText(_translate("MainWindow", ""))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Page_home_conta()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
