# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_login(object):
    def setupUi(self, login):
        login.setObjectName("login")
        login.resize(591, 526)
        login.setMinimumSize(QtCore.QSize(591, 526))
        login.setMaximumSize(QtCore.QSize(591, 526))
        login.setStyleSheet("background-color: rgb(221, 221, 221);")
        self.frame = QtWidgets.QFrame(login)
        self.frame.setGeometry(QtCore.QRect(100, 170, 401, 281))
        self.frame.setStyleSheet("background-color: rgb(235, 255, 234);\n"
"background-color: rgb(221, 223, 255);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.txt_usuario = QtWidgets.QLineEdit(self.frame)
        self.txt_usuario.setGeometry(QtCore.QRect(130, 40, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_usuario.setFont(font)
        self.txt_usuario.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(90, 90, 90);")
        self.txt_usuario.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_usuario.setObjectName("txt_usuario")
        self.txt_senha = QtWidgets.QLineEdit(self.frame)
        self.txt_senha.setEchoMode(QtWidgets.QLineEdit.Password)
        self.txt_senha.setGeometry(QtCore.QRect(130, 80, 151, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.txt_senha.setFont(font)
        self.txt_senha.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(76, 76, 76);")
        self.txt_senha.setAlignment(QtCore.Qt.AlignCenter)
        self.txt_senha.setObjectName("txt_senha")
        self.btn_login = QtWidgets.QPushButton(self.frame)
        self.btn_login.setGeometry(QtCore.QRect(150, 130, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_login.setFont(font)
        self.btn_login.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_login.setStyleSheet("QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_login.setObjectName("btn_login")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(130, 190, 171, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.btn_cadastrar = QtWidgets.QPushButton(self.frame)
        self.btn_cadastrar.setGeometry(QtCore.QRect(150, 220, 111, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_cadastrar.setFont(font)
        self.btn_cadastrar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cadastrar.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(202, 202, 202);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(122, 122, 122);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btn_cadastrar.setObjectName("btn_cadastrar")
        self.line = QtWidgets.QFrame(self.frame)
        self.line.setGeometry(QtCore.QRect(0, 170, 401, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.usuario = QtWidgets.QLabel(login)
        self.usuario.setGeometry(QtCore.QRect(210, -10, 201, 181))
        self.usuario.setText("")
        self.usuario.setPixmap(QtGui.QPixmap("banco_interface/imgs/tinywow_usuario_10961509.png"))
        self.usuario.setObjectName("usuario")

        self.retranslateUi(login)
        QtCore.QMetaObject.connectSlotsByName(login)

    def retranslateUi(self, login):
        _translate = QtCore.QCoreApplication.translate
        login.setWindowTitle(_translate("login", "Form"))
        self.txt_usuario.setPlaceholderText(_translate("login", "Usuário"))
        self.txt_senha.setPlaceholderText(_translate("login", "Senha"))
        self.btn_login.setText(_translate("login", "Login"))
        self.label.setText(_translate("login", "Caso não possua uma conta:"))
        self.btn_cadastrar.setText(_translate("login", "Cadastrar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    login = QtWidgets.QWidget()
    ui = Ui_login()
    ui.setupUi(login)
    login.show()
    sys.exit(app.exec_())
