# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_confirma_excluir.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Page_confirma_excluir(object):
    """
    Essa é uma classe para a pagina de confirmação de exclusão
    """
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(401, 129)
        Form.setMinimumSize(QtCore.QSize(401, 129))
        Form.setMaximumSize(QtCore.QSize(401, 129))
        Form.setStyleSheet("background-color: rgb(221, 221, 221);")

        # Cria um QLabel na janela com texto e formatação específicos
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(70, 30, 261, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")

        # Cria um QPushButton na janela para confirmar a exclusão
        self.btn_confirma = QtWidgets.QPushButton(Form)
        self.btn_confirma.setGeometry(QtCore.QRect(250, 80, 75, 23))
        self.btn_confirma.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_confirma.setStyleSheet("QPushButton{\n"
"    color: rgb(0, 0, 0);\n"
"    background-color: rgb(202, 202, 202);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(122, 122, 122);\n"
"color: rgb(255, 255, 255);\n"
"\n"
"}")
        self.btn_confirma.setObjectName("btn_confirma")
        self.btn_cancelar = QtWidgets.QPushButton(Form)
        self.btn_cancelar.setGeometry(QtCore.QRect(80, 80, 75, 23))
        self.btn_cancelar.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancelar.setStyleSheet("\n"
"\n"
"QPushButton{\n"
"color: rgb(255, 255, 255);\n"
"    background-color: rgb(4, 4, 4);\n"
"border-radius: 10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.btn_cancelar.setObjectName("btn_cancelar")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(10, 60, 381, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        # Chama a função retranslateUi para definir os textos dos elementos da janela
        self.retranslateUi(Form)
        # Conecta sinais de eventos de elementos gráficos a slots (funções)
        QtCore.QMetaObject.connectSlotsByName(Form)

    # é responsável por definir o texto dos widgets em diferentes idiomas, neste caso apenas em português.
    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Tem certeza que deseja excluir sua conta?"))
        self.btn_confirma.setToolTip(_translate("Form", "Essa ação não pode ser desfeita!"))
        self.btn_confirma.setText(_translate("Form", "Sim"))
        self.btn_cancelar.setText(_translate("Form", "Cancelar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Page_confirma_excluir()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
